IDENTIFICATION DIVISION. 
PROGRAM-ID. Ceaser. 

DATA DIVISION.

WORKING-STORAGE SECTION.

	01 default PIC X(26) VALUE "ABCDEFGHIJKLMNOPQRSTUVWXYZ". 
    01 place PIC 9 VALUE 5. 
    
PROCEDURE DIVISION.
BEGIN.
    DISPLAY default 
    DISPLAY place

    PERFORM 
        DISPLAY 'Hello World'
    END-PERFORM.
	
    STOP RUN.
    
ENCRYPT.

	PERFORM 
        DISPLAY 'Hello World'
    END-PERFORM.

SOLVE.
	PERFORM 
	
		PERFORM 
        	DISPLAY 'Hello World'
    	END-PERFORM
    	
        DISPLAY 'Hello World'
    END-PERFORM.

DECRYPT.
	
	PERFORM 
        DISPLAY 'Hello World'
    END-PERFORM.

END PROGRAM Ceaser.